---
- name: Add mongoDB GPG keys
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: Add mongoDB app repository
  become: yes
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
    state: present
    filename: mongodb-org-{{ mongodb_version }}

- name: Install mongoDB
  become: yes
  apt:
    name: mongodb-org
    update_cache: yes

- name: Start mongoDB
  systemd:
    name: mongod
    state: started
    enabled: yes
