---
# Run a command to install roles defined in requirements.yml from ansible galaxy
- hosts: all
  tasks:
  - name: Run ansible galaxy
    connection: local
    command: ansible-galaxy install -r requirements.yml --ignore-errors
    tags: always

- hosts: all
  become: yes
  vars_files:
  - vars/main.yml
  # Use roles directive for self defined roles
  roles:
  - role: sublime-text
    tags: sublime-text
  - role: vscode
    tags: vscode
  - role: docker
    tags: docker
  - role: docker-compose
    tags: docker-compose
  - role: nvidia-docker
    tags: nvidia-docker
  - role: ros
    tags: ros
  - role: gitlab
    tags: gitlab
  - role: gitlab-mattermost
    tags: gitlab-mattermost
  - role: mongodb
    tags: mongodb
  # Use include_role module to dynamically include roles from ansible galaxy
  # Ansible galaxy role must be defined in requirements.yml
  tasks:
  - tags: nodejs
    block:
    - include_role:
        name: geerlingguy.nodejs

