- name: Set up GPG keys
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg

- name: Set up sources.list
  become: yes
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime

- name: Install dependencies
  become: yes
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Install Sublime Text
  become: yes
  apt:
    name: sublime-text
    update_cache: yes

