- name: Set up GPG keys
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: Set up sources.list
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Install dependencies
  become: yes
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Install Visual Studio Code
  become: yes
  apt:
    name: code
    update_cache: yes
