---
- name: Install Docker dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      #- gnupg-curl
      - software-properties-common

- name: Add Docker's official GPG key
  become: true
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Get lsb_release
  shell: lsb_release -sc
  register: lsb_release

- name: Add Docker app repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    state: present

- name: Install Docker
  become: true
  apt:
    name: docker-ce
    update_cache: true

- name: Docker for non-root user
  become: true
  user:
    name: "{{ ansible_user_id }}"
    group: docker
